### ISSUE TITLE
Handle BotoServerError in get_desc()

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#56]
CloudMan 16.05. AWS is having some issues in N. Virginia at the moment and I've noticed the following traceback in the CM log:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mnt/cm/cm/master.py", line 2877, in __monitor
    "for a while; checking now.".format(w_instance.get_desc()))
  File "/mnt/cm/cm/instance.py", line 250, in get_desc
    return "'{id}; {ip}; {sn}'".format(id=self.get_id(), ip=self.get_public_ip(),
  File "/mnt/cm/cm/util/decorators.py", line 42, in df
    return fn(*args, **kwargs)
  File "/mnt/cm/cm/instance.py", line 453, in get_public_ip
    inst.update()
  File "/home/ubuntu/.virtualenvs/CM/local/lib/python2.7/site-packages/boto/ec2/instance.py", line 413, in update
    rs = self.connection.get_all_reservations([self.id], dry_run=dry_run)
  File "/home/ubuntu/.virtualenvs/CM/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 682, in get_all_reservations
    [('item', Reservation)], verb='POST')
  File "/home/ubuntu/.virtualenvs/CM/local/lib/python2.7/site-packages/boto/connection.py", line 1166, in get_list
    response = self.make_request(action, params, path, verb)
  File "/home/ubuntu/.virtualenvs/CM/local/lib/python2.7/site-packages/boto/connection.py", line 1112, in make_request
    return self._mexe(http_request)
  File "/home/ubuntu/.virtualenvs/CM/local/lib/python2.7/site-packages/boto/connection.py", line 1025, in _mexe
    raise BotoServerError(response.status, response.reason, body)
BotoServerError: BotoServerError: 503 Service Unavailable
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>Unavailable</Code><Message>The service is unavailable. Please try again shortly.</Message></Error></Errors><RequestID>0a7779ff-f5ce-46ea-8cdc-9e3a812a10fd</RequestID></Response>
```

**Comment by afgane** [comment]
By the looks of it, this was an AWS issue: http://status.aws.amazon.com/ that has been resolved since then...
<img width="298" alt="screen shot 2016-07-19 at 10 40 30 pm" src="https://cloud.githubusercontent.com/assets/338642/16973478/f782ca6a-4e01-11e6-9b7b-b07cbed2ce54.png">

Let us know if you're still experiencing this and I'll revisit.

**Comment by hackdna** [comment]
Right. This is just to make the code a bit more robust and avoid the tracebacks in the logs.

**Comment by afgane** [comment]
Should be better now.
