### ISSUE TITLE
CloudMan 16.01 and 16.04 fail to start

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#74]
Use either https://beta.launch.usegalaxy.org/catalog/appliance/galaxy-cloud or https://launch.usegalaxy.org/launch to start a new or existing 16.01 or 16.04 clusters (ami-b45e59de).

* Web interface displays:
CloudMan is not running.
It may take a few moments for CloudMan to start after your instance has become available, or there may have been a problem launching it. After a while, you may want to reboot this instance and see if that resolves the problem.
* There is no `/var/log/cloudman/cloudman.log`
* Relevant logs:
```
/var/log/cloudman/cm_boot.log

2017-10-23 19:52:14,984 INFO   cm_boot:240 - << Starting nginx >>
2017-10-23 19:52:14,987 DEBUG  cm_boot:162 - Reconfiguring nginx conf
2017-10-23 19:52:14,990 DEBUG  cm_boot:259 - Creating tmp dir for nginx /mnt/galaxy/upload_store
2017-10-23 19:52:14,990 DEBUG  cm_boot:58  - /usr/local/sbin/nginx is file: False; it's executable: False
2017-10-23 19:52:14,990 DEBUG  cm_boot:58  - /usr/local/bin/nginx is file: False; it's executable: False
2017-10-23 19:52:14,990 DEBUG  cm_boot:58  - /usr/bin/nginx is file: False; it's executable: False
2017-10-23 19:52:14,990 DEBUG  cm_boot:58  - /usr/sbin/nginx is file: True; it's executable: True
2017-10-23 19:52:14,990 DEBUG  cm_boot:268 - Using '/usr/sbin/nginx' as the nginx executable
2017-10-23 19:52:15,089 ERROR  cm_boot:31  - Error running 'ps xa | grep nginx | grep -v grep'. Process returned code '1' and following stderr: ''
2017-10-23 19:52:15,090 DEBUG  cm_boot:270 - nginx not running; will try and start it now
2017-10-23 19:52:17,549 DEBUG  cm_boot:25  - Successfully ran '/usr/sbin/nginx'
2017-10-23 19:52:17,549 DEBUG  cm_boot:279 - Deleting tmp dir for nginx /mnt/galaxy/upload_store
2017-10-23 19:52:17,551 DEBUG  cm_boot:25  - Successfully ran 'rm -rf /mnt/galaxy/upload_store'
2017-10-23 19:52:17,551 DEBUG  cm_boot:339 - Deleting /mnt/cm dir before download
2017-10-23 19:52:17,553 DEBUG  cm_boot:25  - Successfully ran 'rm -rf /mnt/cm'
2017-10-23 19:52:17,553 INFO   cm_boot:341 - << Downloading CloudMan >>
2017-10-23 19:52:17,553 DEBUG  cm_boot:43  - Checking existence of directory '/mnt/cm'
2017-10-23 19:52:17,553 DEBUG  cm_boot:46  - Creating directory '/mnt/cm'
2017-10-23 19:52:17,553 DEBUG  cm_boot:48  - Directory '/mnt/cm' successfully created.
2017-10-23 19:52:17,553 DEBUG  cm_boot:346 - Using user-provided default bucket: cloudman
2017-10-23 19:52:17,553 INFO   cm_boot:308 - connecting to Amazon S3 at http://s3.amazonaws.com/
2017-10-23 19:52:17,554 DEBUG  cm_boot:333 - Got boto S3 connection: S3Connection:s3.amazonaws.com
2017-10-23 19:52:17,554 DEBUG  cm_boot:203 - Checking if key 'cm.tar.gz' exists in bucket 'cm-298bcca1dd946c4f308a30e9527cdbc9'
2017-10-23 19:52:17,570 DEBUG  cm_boot:183 - Getting file cm.tar.gz from bucket cloudman
2017-10-23 19:52:17,570 DEBUG  cm_boot:187 - Attempting to retrieve file 'cm.tar.gz' from bucket 'cloudman'
2017-10-23 19:52:17,734 INFO   cm_boot:190 - Successfully retrieved file 'cm.tar.gz' from bucket 'cloudman' via connection 's3.amazonaws.com' to '/mnt/cm/cm.tar.gz'
2017-10-23 19:52:17,734 INFO   cm_boot:363 - Retrieved CloudMan (cm.tar.gz) from bucket 'cloudman' via local s3 connection
2017-10-23 19:52:17,734 INFO   cm_boot:407 - << Unpacking CloudMan from /mnt/cm/cm.tar.gz >>
2017-10-23 19:52:17,799 DEBUG  cm_boot:430 - virtualenv does not exist
2017-10-23 19:52:20,596 DEBUG  cm_boot:25  - Successfully ran 'virtualenv /opt/cloudman/boot/.venv'
2017-10-23 19:52:20,596 DEBUG  cm_boot:450 - Copying user data file from '/opt/cloudman/boot/userData.yaml' to '/mnt/cm/userData.yaml'
2017-10-23 19:52:20,596 INFO   cm_boot:453 - << Starting CloudMan in /mnt/cm >>
2017-10-23 19:52:20,596 DEBUG  cm_boot:428 - virtualenv seems to be installed
2017-10-23 19:52:36,363 ERROR  cm_boot:31  - Error running '. /opt/cloudman/boot/.venv/bin/activate && cd /mnt/cm; pip install -r /mnt/cm/requirements.txt; sh run.sh --daemon --log-file=/var/log/cloudman/cloudman.log'. Process returned code '1' and following stderr: 'Traceback (most recent call last):
  File "./scripts/paster.py", line 22, in <module>
    from paste.script import command
ImportError: No module named paste.script
'
2017-10-23 19:52:36,363 INFO   cm_boot:513 - ---> /opt/cloudman/boot/cm_boot.py done <---


/root/.pip/pip.log

  Downloading from URL https://pypi.python.org/packages/bf/da/6a9f49cc7a970380c8235b3adab0c08c7c3d4814876f7383b33e3882a577/cryptography-2.1.1.tar.gz#md5=fa98118b468020349a798776aac6d572 (from https://pypi.python.org/simple/cryptography/)
  Running setup.py (path:/opt/cloudman/boot/.venv/build/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
  Removing temporary dir /opt/cloudman/boot/.venv/build...
Command python setup.py egg_info failed with error code 1 in /opt/cloudman/boot/.venv/build/cryptography
Exception information:
Traceback (most recent call last):
  File "/opt/cloudman/boot/.venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/opt/cloudman/boot/.venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/opt/cloudman/boot/.venv/local/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/opt/cloudman/boot/.venv/local/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/opt/cloudman/boot/.venv/local/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /opt/cloudman/boot/.venv/build/cryptography
```

It appears that the [error is due to an outdated version of pip](https://github.com/pyca/cryptography/blob/master/docs/faq.rst#installing-cryptography-fails-with-invalid-environment-marker-python_version--3) and it is possible to update pip and start the CloudMan process manually:
```
sudo su -
. /opt/cloudman/boot/.venv/bin/activate
pip install -U pip setuptools
pip install -r /mnt/cm/requirements.txt
cd /mnt/cm
sh run.sh --daemon --log-file=/var/log/cloudman/cloudman.log
```

However, cluster shows the same error after restart.

**Comment by afgane** [comment]
Just an FYI, I'm at a conference until Thursday and it's likely I won't be able to get a chance to look at this until after I'm back...

**Comment by hackdna** [comment]
No problem, thanks for heads up.

**Comment by hackdna** [comment]
It looks like this is due to an [issue with cryptography module](https://github.com/pyca/cryptography/issues/3965). Would it be possible to update pip and setuptools or set cryptography package version to 2.0 or lower?

**Comment by afgane** [comment]
It looks like it's working now. In addition to the two linked commits, I also updated the original `https://cloudman.s3.amazonaws.com/cm.tar.gz` to include `cryptography==2.0` in it's `requirements.txt` file and uploaded it as `https://cloudman.s3.amazonaws.com/cm16.tar.gz`. That change is not committed anywhere though so adding it here.

After an instance launches, it takes a while for the virtualenv to be set up and you're likely to encounter the following screen for a few minutes following a launch but in about 5 minutes, CloudMan should load.

<img width="603" alt="screen shot 2017-11-01 at 3 30 20 pm" src="https://user-images.githubusercontent.com/338642/32293688-502789d2-bf1a-11e7-9b29-4ecf02a8205f.png">

**Comment by hackdna** [comment]
Thank you. So, will this fix apply to our saved clusters automatically or would I need to launch a new one and share it again? Do I need to specify `https://cloudman.s3.amazonaws.com/cm16.tar.gz` anywhere?

**Comment by afgane** [comment]
It will not apply to saved clusters automatically. The easiest thing to do would be to download `https://cloudman.s3.amazonaws.com/cm16.tar.gz` and then upload it to your saved cluster's bucket to replace `cm.tar.gz` that's already there.

**Comment by hackdna** [comment]
Thanks. I've downloaded the new `cm16.tar.gz` and uploaded it to replace the existing `cm.tar.gz` in my saved cluster bucket (`cm-656633c6a81b5f6e5d1d9e79233e680a/shared/2017-10-25--22-50`). Then I've started a cluster using that shared cluster string and waited for about 5 mins but CloudMan didn't come up. Pip log shows the same problem with the cryptography package and cm_boot.log says:
```
2017-11-02 19:29:12,399 DEBUG  cm_boot:204 - Checking if key 'cm.tar.gz' exists in bucket 'cm-5b1c20b8f089bcb01a853b1ac5bc455a'
2017-11-02 19:29:12,414 DEBUG  cm_boot:184 - Getting file cm.tar.gz from bucket cloudman
2017-11-02 19:29:12,414 DEBUG  cm_boot:188 - Attempting to retrieve file 'cm.tar.gz' from bucket 'cloudman'
2017-11-02 19:29:12,566 INFO   cm_boot:191 - Successfully retrieved file 'cm.tar.gz' from bucket 'cloudman' via connection 's3.amazonaws.com' to '/mnt/cm/cm.tar.gz'
2017-11-02 19:29:12,566 INFO   cm_boot:371 - Retrieved CloudMan (cm.tar.gz) from bucket 'cloudman' via local s3 connection
2017-11-02 19:29:12,566 INFO   cm_boot:416 - << Unpacking CloudMan from /mnt/cm/cm.tar.gz >>
2017-11-02 19:29:12,630 DEBUG  cm_boot:439 - virtualenv does not exist
2017-11-02 19:29:14,817 DEBUG  cm_boot:26  - Successfully ran 'virtualenv /opt/cloudman/boot/.venv'
2017-11-02 19:29:14,817 DEBUG  cm_boot:459 - Copying user data file from '/opt/cloudman/boot/userData.yaml' to '/mnt/cm/userData.yaml'
2017-11-02 19:29:14,818 INFO   cm_boot:462 - << Starting CloudMan in /mnt/cm >>
2017-11-02 19:29:14,818 DEBUG  cm_boot:437 - virtualenv seems to be installed
2017-11-02 19:29:31,852 ERROR  cm_boot:32  - Error running '. /opt/cloudman/boot/.venv/bin/activate && cd /mnt/cm; pip install -r /mnt/cm/requirements.txt; sh run.sh --daemon --log-file=/var/log/cloudman/cloudman.log'. Process returned code '1' and following stderr: 'Traceback (most recent call last):
  File "./scripts/paster.py", line 22, in <module>
    from paste.script import command
ImportError: No module named paste.script
'
2017-11-02 19:29:31,852 INFO   cm_boot:522 - ---> /opt/cloudman/boot/cm_boot.py done <---
```
Any ideas?

**Comment by afgane** [comment]
Ohh, if it’s a shared cluster, the `cm.tar.gz` to replace is the one in the shared cluster folder. So will need to get access to the original cluster's bucket (the one that was shared), find the appropriate folder for the share, and replace the file there.

**Comment by hackdna** [comment]
This is what I've done previously: I've uploaded the new `cm.tar.gz` into the folder for share (`cm-656633c6a81b5f6e5d1d9e79233e680a/shared/2017-10-25--22-50`).

Now, I've also uploaded the new `cm.tar.gz`  into the "root" of the shared cluster bucket (`cm-656633c6a81b5f6e5d1d9e79233e680a`). However, cm_boot is still looking for that file in `cm-5b1c20b8f089bcb01a853b1ac5bc455a` instead (see the log above). This bucket doesn't exist in my account but it does exist somewhere on AWS (I can't create it).

**Comment by hackdna** [comment]
OK, this works but only after the new `cm.tar.gz` is also copied manually to the bucket of the new cluster that is created from the shared cluster string.

**Comment by afgane** [comment]
I looked at this some this morning but ran out of time so will have to get back to it. That `cm-5b1c20b8f089bcb01a853b1ac5bc455a` bucket - it would only make sense for that to be the bucket of the newly created clone, which is expected to be empty. I'll have to trace the sharing path as I don't recall all the bits of it any more... Glad you figured out how to get a working system for the time being.

**Comment by hackdna** [comment]
Yes, thanks for your help. We are OK for now but going to prioritize upgrading to the latest version of CloudMan as soon as project schedule permits.

**Comment by nuwang** [comment]
Closing because old version.
